WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalog.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

WebBooks/catalog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('author/', views.AutorListView.as_view(), name='author-list'),
    path('author/<int:pk>/', views.AutorDetailView.as_view(), name='autor-detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Input genre book',
                            verbose_name='Genre book')
    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Input language book',
                            verbose_name='Language book')
    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Input name of publisher',
                            verbose_name='Publisher')
    def __str__(self):
        return self.name


class Autor(models.Model):
    first_name = models.CharField(max_length=100,
                            help_text='Input name autor',
                            verbose_name='Name autor')
    last_name = models.CharField(max_length=100,
                            help_text='Input lastname autor',
                            verbose_name='Lastname autor')
    date_of_birth = models.DateField(
        help_text='Input date of birth',
        verbose_name='Date of birth',
        null=True, blank=True
    )
    about = models.TextField(help_text='Input info about autor',
                             verbose_name='About autor')
    photo = models.ImageField(upload_to='images',
                              help_text='Input foto autor',
                              verbose_name='Foto autor',
                              null=True, blank=True)

    def __str__(self):
        return self.last_name

class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text='Input name book',
                             verbose_name='Name book')
    genre = models.ForeignKey('Genre',
                              on_delete=models.CASCADE,
                              help_text="Choice genre for book",
                              verbose_name='Genre book', null=True)
    language = models.ForeignKey('Language',
                              on_delete=models.CASCADE,
                              help_text="Choice language for book",
                              verbose_name='Language book', null=True)
    publisher = models.ForeignKey('Publisher',
                              on_delete=models.CASCADE,
                              help_text="Choice publisher",
                              verbose_name='Publisher', null=True)
    year = models.CharField(max_length=4,
                            help_text='Choice year publish')
    author = models.ManyToManyField('Autor',
                                    help_text='Choice author(s) book',
                                    verbose_name='Autor(s) book')
    summary = models.TextField(max_length=1000,
                               help_text='Input summary of book',
                               verbose_name='Annotation of book')
    ibsn = models.CharField(max_length=13,
                            help_text='Must input 13 char',
                            verbose_name='IBSN book')
    price = models.DecimalField(decimal_places=2, max_digits=7,
                                help_text='Input price of book',
                                verbose_name='Price (usd.)')
    photo = models.ImageField(upload_to='images',
                              help_text='Input image book',
                              verbose_name='Image book')

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = 'Autors'



class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Input status exemplar of book",
                            verbose_name='STATUS')
    def __str__(self):
        return self.name

class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(
        max_length=20,
        null=True,
        help_text='Input inventar number exemplar',
        verbose_name='Inventar number')
    status = models.ForeignKey('Status',
                               on_delete=models.CASCADE,
                               null=True,
                               help_text='Change state exemplar',
                               verbose_name='Status exemplar book')
    due_back = models.DateField(null=True, blank=True,
                                help_text='Input end time status',
                                verbose_name='Date of end status')

    class Meta:
        ordering = ['due_back']
    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

WebBooks/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Autor, BookInstance
from django.views.generic import ListView, DetailView

class AutorDetailView(DetailView):
    model = Autor

class AutorListView(ListView):
    model = Autor
    paginate_by = 4

class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'

class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 5

def index(request):
    text_head = 'На нашем сайте вы можете получить книги в электронном виде'
    books = Book.objects.all()
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact=2).count()
    authors = Autor.objects
    num_authors = Autor.objects.count()
    context = {'text_head': text_head,
               'books': books, 'num_books': num_books,
               'num_instances': num_instances,
               'num_instances_available': num_instances_available,
               'authors': authors, 'num_authors': num_authors}
    return render(request, 'catalog/index.html', context)


def about(request):
    text_head = 'Сведения о компании'
    name = 'ООО "Интелектуальные информационные системы"'
    rab1 = 'Разаработка проложений на основе систем искусственного интелекта'
    rab2 = 'Распознавание обьектов дорожной инфраструктуры'
    rab3 = 'Создание графических АРТ-обьектов на основе систем искусственного интелекта'
    rab4 = 'Создание цифровых интерактивных книгб учебных пособий фвтоматизирываных обучающих систем'
    context = {
        'text_head': text_head, 'name': name,
        'rab1': rab1, 'rab2': rab2, 'rab3': rab3, 'rab4': rab4
    }
    return render(request, 'catalog/about.html', context)

def contact(request):
    text_head = 'Контакты'
    name = 'ООО "Интелектуальные информационные системы"'
    address = 'Днепр, Спасская 221а'
    tel = '380976543123'
    email = 'gwondoys@gmail.com'
    context = {
        'text_head': text_head,
        'name': name, 'address': address,
        'tel': tel, 'email': email
    }
    return render(request, 'catalog/contact.html', context)

WebBooks/templates/catalog/about.html
{% extends 'catalog/base.html' %}
<head>
    {% load static %}
</head>

{% block content %}
    <!-- Карусель -->
    <div class="container">
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="text-white">Искусственный интелект</h2>
                        <h3 class="text-white">{{rab1}}</h3>
                    </div>
                </div>

                <div class="carousel-item">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="text-white">Компьтерное зрение</h2>
                        <h3 class="text-white">{{rab2}}</h3>
                    </div>
                </div>

                <div class="carousel-item">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="text-white">Арт обьекты</h2>
                        <h3 class="text-white">{{rab3}}</h3>
                    </div>
                </div>

                <div class="carousel-item">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 class="text-white">Электронные книги</h2>
                        <h3 class="text-white">{{rab4}}</h3>
                    </div>
                </div>
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Предыдущий</span>
            </button>

            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Следующий</span>
            </button>

        </div>
    </div>
    <!--Конец карусели-->

    <div class="container-fluid">
        <h4 class="text-center">{{ text_head }}</h4>
        <div class="row my-2 text-center">
            <div class="col-5"></div>
            <div class="col-5"></div>
        </div>
        <div class="row my-2 text-primary text-center">
            <h3>{{ name }}</h3>
        </div>
        <div class="row my-2 text-white text-start">
            <div class="col mx-2 my-2 bg-primary">{{rab1}}</div>
            <div class="col mx-2 my-2 bg-primary">{{rab2}}</div>
            <div class="col mx-2 my-2 bg-primary">{{rab3}}</div>
            <div class="col mx-2 my-2 bg-primary">{{rab4}}</div>
        </div>
    </div>

    <div class="row my-2 text-center">
        <!-- Пустые колонки слева от аккордеона -->
        <div class="col-3"></div>
        <!-- 6 колонок с аккордеоном -->
        <div class="col-6 text-start">
            <!-- Аккордеон -->
            <div class="accordion" id="accordionExample">
                <!-- Аккордеон элемент 1 -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#collapseOne"
                                aria-expanded="true" aria-controls="collapseOne">
                            Искусственный интелект
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse"
                            aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <strong>Разработка под ключ.</strong>
                            Разрабатываем информационные комплексы на базе систем искусственного интеллекта
                        </div>
                    </div>
                </div>

                 <!-- Аккордеон элемент 2 -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo"
                                aria-expanded="true" aria-controls="collapseTwo">
                            Дорожная инфраструктура
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse"
                            aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <strong>Системы распознавания.</strong>
                            Разрабатываем системы распознавания обьктов дорожной инфраструктуры
                            с использованием нейронных сетей.
                        </div>
                    </div>
                </div>

                <!-- Аккордеон элемент 3 -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button collapsed" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#collapseThree"
                                aria-expanded="true" aria-controls="collapseThree">
                            Арт-обьекты
                        </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse"
                            aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <strong>Обработка изображений.</strong>
                            Создаем уникальные изображения с использованием систем машинного
                            зрения и искусственного интелекта.
                        </div>
                    </div>
                </div>


                <!-- Аккордеон элемент 4 -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingFour">
                        <button class="accordion-button collapsed" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#collapseFour"
                                aria-expanded="true" aria-controls="collapseFour">
                            Интерактивные электронные книги
                        </button>
                    </h2>
                    <div id="collapseFour" class="accordion-collapse collapse"
                            aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <strong>Интерактивное обучение.</strong>
                            Разрабатываем интерактивные обучающие пособия, учебники, электронные
                            книги для студентов и школьников.
                        </div>
                    </div>
                </div>
                <!--Аккордеон конец-->
            </div>
        </div>
        <!--пустые колонки справа от аккордеона-->
        <div class="col-3"></div>
    </div>

{% endblock content %}

WebBooks/templates/catalog/autor_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container text-start">
    <div class="row my-2">
        <h4>{{ autor.first_name }} {{ autor.last_name }}</h4>
        <p>Родился - {{ autor.date_of_birth }}</p>
        <p>Фото (портрет)</p>
        <p><img src="{{ autor.photo.url }}" alt="connect" style="max-height:200px"></p>
        <div class="row my-2">
            <div class="col-2 my-2">
                <a href="{{ autor.photo.url }}" class="btn btn-primary" target="_blank">Показать</a>
            </div>
        </div>
        <div class="row my-2">
            {{ autor.about }}
        </div>
    </div>
</div>


{% endblock content %}

WebBooks/templates/catalog/autor_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<h4>Список авторов книг</h4>
{% if autor_list %}
    <table class="table table-striped table-boarded text-start">
        <thead>
            <tr>
                <th>Автор</th>
                <th>Фото</th>
                <th>Показать фото</th>
            </tr>
        </thead>
        <tbody>
        {% for author in autor_list.all %}
            <tr>
                <td><a href="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</a></td>
                <td><img src="{{ author.photo.url }}" alt="connect" style="max-height:100px"></td>
                <td><a href="{{ author.photo.url }}" class="btn btn-primary" target="_blank">Показать</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endif %}


{% endblock content %}

WebBooks/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script defer src="/static/js/bootstrap.bundle.min.js"></script>
    <title>Title</title>
</head>
<body>
    <div class="container-fluid p-1 bg-primary text-white text-center">
        <div class="row">

            <div class="col-10">
                <h3>Мир книг - печатные и электонные интерактивные книги</h3>
            </div>

        </div>

    </div>
    <div class="container-fluid">
        <div class="row bg-dark text-center">
            <h6>
                <a href="{% url 'index' %}">MAIN PAGE</a>
                <a href="{% url 'about' %}">ABOUT</a>
                <a href="{% url 'contact' %}">CONTACTS</a>
            </h6>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row text-center text-primary fs-1 fw-bold">
            <div>{% block header %}{% endblock header %}</div>
        </div>
        <div class="row text-center text-body">
            <div class="col-2 bg-light">
                {% block sidebar %}
                <nav class="nav flex-column">
                    <a class="nav-link" href="{% url 'books' %}">Все книги</a>
                    <a class="nav-link" href="{% url 'author-list' %}">Все авторы</a>
                </nav>
                {% endblock sidebar %}
            </div>
            <div class="col-10">
                <div class="row text-center">
                    {% block content %}
                    {% endblock content %}

                    <!-- PAGINATOR -->
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.paginator.num_pages > 1  %}
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; Первая</a>
                                    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                                {% endif %}
                                <span class="current">
                                    Стр. {{ page_obj.number }}
                                    из {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                                    <a href="?page={{ page_obj.paginator.num_pages }}"> Предыдущая &raquo; </a>
                                {% endif %}
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container-fluid">
        <div class="row bg-primary text-center text=white lh-1">
            {% block footer %}
                <p>Copyright 000 'Intelectual information system', 2025. All rights reversed</p>
            {% endblock footer %}
        </div>
    </div>


</body>
</html>

WebBooks/templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container text-start">
    <div class="row my-2">
        <h1> Название книги - "{{ book.title }}"</h1>
    </div>
    <div class="row my-2">
        <p><strong>Автор:</strong></p>
        {% for author in book.author.all %}
            <a href="">{{ author.first_name }} {{ author.last_name }}</a>
        {% endfor %}
    </div>
    <img src="{{book.photo.url}}" alt="connect" style="max-height:200px">
    <a href="{{ book.photo.url }}" class="btn btn-primary"
       target="_blank">Показать</a>
    <div class="row my-2">
        <div class="col">
            <p><strong>Цена:</strong>{{ book.price }}</p>
        </div>
    </div>
    <div class="row my-2">
        <p><strong>Аннотация:</strong>{{ book.summary }}</p>
    </div>

    <div class="row my-2">
        <div class="col mx-2 bg-primary text-white">
            <p><strong>Жанр:</strong>{{ book.genre }}</p>
        </div>
    </div>

    <div class="col mx-2 bg-primary text-white">
        <p><strong>IBSN:</strong>{{ book.ibsn }}</p>
    </div>

    <div class="col mx-2 bg-primary text-white">
        <p><strong>Язык:</strong>{{ book.language }}</p>
    </div>

    <div class="col mx-2 bg-primary text-white">
        <p><strong>Издательство:</strong>{{ book.publisher }}</p>
    </div>
</div>

<div style="margin-left:20px; margin-top:10px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr>
        <p class="text-muted">
            <strong>Инвентарный номер:</strong>
            {{ copy.id }}
        </p>
        <p class="success">
            <strong>Статус экземпляра книги:</strong>
            {{ copy.status }}
        </p>
    {% endfor %}
</div>


{% endblock content %}

WebBooks/templates/catalog/book_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-center text-dark lh-2">
        <h4>Список книг в БД</h4>
    </div>
    {% if books %}
        <table class="table table-striped table-bordered text-start">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Жанр</th>
                    <th>Обложка</th>
                    <th>Показать обложку</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                    <tr>
                        <td><a href="{{ book.id }}">{{ book.title }}</a></td>
                        <td>{{ book.display_author }}</td>
                        <td>{{ book.genre }}</td>
                        <td><img src="{{book.photo.url}}" alt="connect"
                                 style="max-height:100px"></td>
                        <td><a href="{{book.photo.url}}"
                                 class="btn btn-primary"
                                 target="_blank">Показать</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>В базе нет книг</p>

    {% endif %}


{% endblock content %}

WebBooks/templates/catalog/contact.html
{% extends 'catalog/base.html' %}
<head>
    {% load static %}
</head>
{% block content %}
<div class="container-fluid">
    <div class="row my-2 text-center">
        <div class="col-5"></div>

        <div class="col-5"></div>
    </div>

    <div class="row my-2 text-primary text-center">
        <h3>{{ name }}</h3>
    </div>

    <div class="row my-2 text-muted">
        <h4 class="text-center">{{ text_head }}</h4>
    </div>

    <div class="row my-2">
        <!--пустые колонки слева от таблицы-->
        <div class="col-3"></div>
        <div class="col-6">
            <table class="table table-striped table-boarded text-start">
                <thead>
                    <tr>
                        <th>Адрес</th>
                        <th>Телефон</th>
                        <th>e-mail</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ address }}</td>
                        <td>{{ tel }}</td>
                        <td>{{ email }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!--пустые колонки справа от таблиицы-->

    </div>
</div>



{% endblock content %}

WebBooks/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% block title %}World Book{% endblock title %}
{% block header %}
    <h5>{{ text_head }}</h5>
{% endblock header %}

{% block content %}
    <div class="container-fluid my-2">
        <div class="row bg-success text-white mx-2">
            <div class="col text-center">
                <p>Добро пожаловать на сайт <em>Мир книг</em>. Это очень
                простой веб сайт, написаный на Django o Bootsrtap.
                Разработан на Python в качестве учебного примера с
                использованием PyCharm</p>
            </div>

        </div>
        <div class="row text-center text-dark lh-2">
            <h4>Сведения из базы данных</h4>
        </div>
        <div class="row my-2 text-white">
            <div class="col mx-2 bg-primary"> Количество книг - {{ num_books}}</div>
            <div class="col mx-2 bg-primary"> На складе в наличии - {{ num_instances}}</div>
            <div class="col mx-2 bg-primary"> Количество авторов -  {{ num_authors}}</div>
        </div>
        <div class="row text-center text-dark lh-2">
            <h3>Книги</h3>
        </div>
        {% if num_books > 0 %}
            <div class="row my-2">
                {% for obj in books %}
                    <div class="card my-1 me-2" style="width: 9rem;">
                        <img src="{{ obj.photo.url }}" class="card-img-top">
                        <div class="card-body">
                            <p class="card-text small">
                                {{obj.title}} , price {{obj.price}} grn.
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock content %}